spring:
  application:
    name: ecommerce
  datasource:
    url: jdbc:mysql://${MYSQL_URL:localhost}:${MYSQL_PORT:3308}/${MYSQL_DATABASE:ecommerce}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_ROOT_PASSWORD:admin123}
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "${GOOGLE_CLIENT_ID:}"
            client-secret: "${GOOGLE_CLIENT_SECRET:}"
            redirect-uri: "${GOOGLE_REDIRECT_URI:}"
            auth-uri: "https://accounts.google.com/o/oauth2/v2/auth"
            token-uri: "https://www.googleapis.com/oauth2/v3/token"
            user-info-uri: "https://www.googleapis.com/oauth2/v3/userinfo"
            scope:
              - email
              - public_profile

          facebook:
            client-id: "${FACEBOOK_CLIENT_ID:}"
            client-secret: "${FACEBOOK_CLIENT_SECRET:}"
            redirect-uri: "${FACEBOOK_REDIRECT_URI:}"
            auth-uri: "https://www.facebook.com/v11.0/dialog/oauth"
            token-uri: "https://graph.facebook.com/v11.0/oauth/access_token"
            user-info-uri: "https://graph.facebook.com/me?fields=id,name,email,picture.type(large)"
            scope:
              - email
              - public_profile

cybersoft:
  username: admin
  password: admin

jwt:
  secret: OWE0ZjJjOGQzYjdhMWU2ZjQ1YzhhMGIzZjI2N2Q4YjFkNGU2ZjNjOGE5ZDJiNWY4ZTNhOWM4YjVmNnY4YTNkOQ==
  expiration: 86400

upload:
  path: D:\Practice\Java\ecommerce\images123

custom:
  redis:
    host: ${REDIS_URL:localhost}
    port: ${REDIS_PORT:6380}
    password: ${REDIS_PASSWORD:null}